In [1]:
import pandas as pd

In [2]:
path1 = "./Dados/Covid/HIST_PAINEL_COVIDBR_2020_Parte1_22ago2021.csv"
path2 = "./Dados/Covid/HIST_PAINEL_COVIDBR_2020_Parte2_22ago2021.csv"
path3= "./Dados/Covid/HIST_PAINEL_COVIDBR_2021_Parte1_22ago2021.csv"
path4 = "./Dados/Covid/HIST_PAINEL_COVIDBR_2021_Parte2_22ago2021.csv"

path = [path1,path2,path3,path4]


df_from_each_file = (pd.read_csv(f,error_bad_lines=False,sep=';') for f in path)
df = pd.concat(df_from_each_file, ignore_index=True)

df

D:\Arquivos de programas(HD)\Python\Python39\lib\site-packages\pandas\core\reshape\concat.py:348: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  objs = list(objs)

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
0,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-25,9,210147125.0,0.0,0,0,0,NaN,NaN,NaN
1,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-26,9,210147125.0,1.0,1,0,0,NaN,NaN,NaN
2,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-27,9,210147125.0,1.0,0,0,0,NaN,NaN,NaN
3,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-28,9,210147125.0,1.0,0,0,0,NaN,NaN,NaN
4,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-29,9,210147125.0,2.0,1,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2889029,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2021-08-18,33,3015268.0,461422.0,582,9863,14,NaN,NaN,1.0
2889030,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2021-08-19,33,3015268.0,461925.0,503,9878,15,NaN,NaN,1.0
2889031,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2021-08-20,33,3015268.0,462687.0,762,9887,9,NaN,NaN,1.0
2889032,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2021-08-21,33,3015268.0,463530.0,843,9898,11,NaN,NaN,1.0
2889033,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2021-08-22,34,3015268.0,463942.0,412,9914,16,NaN,NaN,1.0

In [8]:
df = df.drop(columns=['coduf','codmun','codRegiaoSaude','nomeRegiaoSaude','Recuperadosnovos','emAcompanhamentoNovos','interior/metropolitana'])
df

,regiao,estado,municipio,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos
0,Brasil,NaN,NaN,2020-02-25,9,210147125.0,0.0,0,0,0
1,Brasil,NaN,NaN,2020-02-26,9,210147125.0,1.0,1,0,0
2,Brasil,NaN,NaN,2020-02-27,9,210147125.0,1.0,0,0,0
3,Brasil,NaN,NaN,2020-02-28,9,210147125.0,1.0,0,0,0
4,Brasil,NaN,NaN,2020-02-29,9,210147125.0,2.0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
2889029,Centro-Oeste,DF,Brasília,2021-08-18,33,3015268.0,461422.0,582,9863,14
2889030,Centro-Oeste,DF,Brasília,2021-08-19,33,3015268.0,461925.0,503,9878,15
2889031,Centro-Oeste,DF,Brasília,2021-08-20,33,3015268.0,462687.0,762,9887,9
2889032,Centro-Oeste,DF,Brasília,2021-08-21,33,3015268.0,463530.0,843,9898,11
2889033,Centro-Oeste,DF,Brasília,2021-08-22,34,3015268.0,463942.0,412,9914,16

In [3]:
print(df["data"].min())
print(df["data"].max())

2020-02-25
2021-08-22

In [4]:
#Comprovando que existe 545 dias únicos
print("Dias unicos no DF: "+ str(len(df[df['regiao'] == 'Brasil']['data'].unique())))
print("Número de linhas do datarame correspondente a data: "+str(len(df[df['regiao'] == 'Brasil']['data'])))

Dias unicos no DF: 545
Número de linhas do datarame correspondente a data: 545

In [5]:
#As datas do município começam em '2020-03-27' e vão até '2021-08-22'
print(df[df['municipio'] == "Belo Horizonte"]["data"].min())
print(df[df['municipio'] == "Belo Horizonte"]["data"].max())

2020-03-27
2021-08-22

In [6]:
df[(df['regiao'] == "Centro-Oeste") & (df['municipio'].isna()) & (df['estado'] == 'GO') & (df['casosAcumulado'] != 0 )]

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
4125,Centro-Oeste,GO,NaN,52,NaN,NaN,NaN,2020-03-13,11,7018354.0,3.0,3,0,0,NaN,NaN,NaN
4126,Centro-Oeste,GO,NaN,52,NaN,NaN,NaN,2020-03-14,11,7018354.0,3.0,0,0,0,NaN,NaN,NaN
4127,Centro-Oeste,GO,NaN,52,NaN,NaN,NaN,2020-03-15,12,7018354.0,3.0,0,0,0,NaN,NaN,NaN
4128,Centro-Oeste,GO,NaN,52,NaN,NaN,NaN,2020-03-16,12,7018354.0,3.0,0,0,0,NaN,NaN,NaN
4129,Centro-Oeste,GO,NaN,52,NaN,NaN,NaN,2020-03-17,12,7018354.0,6.0,3,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2592653,Centro-Oeste,GO,NaN,52,NaN,NaN,NaN,2021-08-18,33,7018354.0,787760.0,4023,21908,65,NaN,NaN,NaN
2592654,Centro-Oeste,GO,NaN,52,NaN,NaN,NaN,2021-08-19,33,7018354.0,791823.0,4063,21974,66,NaN,NaN,NaN
2592655,Centro-Oeste,GO,NaN,52,NaN,NaN,NaN,2021-08-20,33,7018354.0,794639.0,2816,22025,51,NaN,NaN,NaN
2592656,Centro-Oeste,GO,NaN,52,NaN,NaN,NaN,2021-08-21,33,7018354.0,796548.0,1909,22082,57,NaN,NaN,NaN
2592657,Centro-Oeste,GO,NaN,52,NaN,NaN,NaN,2021-08-22,34,7018354.0,797107.0,559,22089,7,NaN,NaN,NaN